# Generated by Django 6.0 on 2025-12-09 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0003_shift_score_usershopscore"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together=set(),
        ),
    ]
