# Generated by Django 6.0 on 2025-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0004_alter_shift_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="role",
            field=models.CharField(
                choices=[("main", "Duty"), ("backup", "Standby")],
                default="main",
                max_length=10,
            ),
        ),
    ]
