# Generated by Django 6.0 on 2025-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0005_alter_shift_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="score_breakdown",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
