# Generated by Django 6.0 on 2025-12-07 01:41

from django.db import migrations

def convert_superusers_to_admin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Filter for users where is_superuser is True and tier is NOT 'administrator'
    # Although the requirement says "Convert all existing SuperUsers", checking for not administrator is an optimization.
    # But strictly speaking, we can just update all superusers.
    superusers = User.objects.filter(is_superuser=True)
    count = superusers.update(tier='administrator')
    print(f"\nUpdated {count} superusers to administrator tier.")

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_nickname"),
    ]

    operations = [
        migrations.RunPython(convert_superusers_to_admin),
    ]
