# Generated by Django 6.0 on 2025-12-07 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_convert_superusers_to_admin"),
        ("attendance", "0002_shopoperatinghours"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="applicable_shops",
            field=models.ManyToManyField(
                blank=True, related_name="applicable_staff", to="attendance.shop"
            ),
        ),
        migrations.CreateModel(
            name="PasswordResetRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("new_username", models.CharField(max_length=150)),
                ("new_password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_reset_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
