# Generated by Django 6.0 on 2025-12-11 03:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_applicable_shops_passwordresetrequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("creation", "Account Created"),
                            ("promotion", "Promotion/Demotion"),
                            ("suspension", "Suspension/Activation"),
                            ("update", "Details Updated"),
                            ("assignment", "Shop Assignment Changed"),
                            ("password_reset", "Password Reset"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
