# Generated by Django 6.0 on 2025-12-11 03:32

from django.db import migrations

def backfill_creation_logs(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    AccountActionLog = apps.get_model('accounts', 'AccountActionLog')

    users = User.objects.all()
    logs_to_create = []

    for user in users:
        # Check if log already exists to be safe
        if not AccountActionLog.objects.filter(user=user, action_type='creation').exists():
            logs_to_create.append(
                AccountActionLog(
                    user=user,
                    action_type='creation',
                    details='Account created (Backfilled)',
                    timestamp=user.date_joined,
                    performed_by=None
                )
            )

    if logs_to_create:
        AccountActionLog.objects.bulk_create(logs_to_create)

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_accountactionlog"),
    ]

    operations = [
        migrations.RunPython(backfill_creation_logs),
    ]
