# Generated by Django 6.0 on 2025-12-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_shopoperatinghours"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="remarks",
            field=models.TextField(
                blank=True,
                help_text="Stores manual override history and remarks.",
                null=True,
            ),
        ),
    ]
