# Generated by Django 6.0 on 2025-12-24 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_area_user_area"),
        ("attendance", "0003_timelog_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shops",
                to="accounts.area",
            ),
        ),
    ]
